# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7LcBUkfRHLD_j-UoaPHRLsVok4cp-Nv
"""



# streamlit_app.py
import streamlit as st

# Configure the main page settings for the Streamlit application.
# This should be the very first Streamlit command in your script.
st.set_page_config(
    page_title="Quebec Road Accident Analysis", # Title for the browser tab
    page_icon="🚗",                        # Icon for the browser tab
    layout="wide",                         # Use a wide layout for the app
    initial_sidebar_state="expanded"       # Keep the sidebar expanded by default
)

def main():
    """
    This function defines the content for the main entry point of your Streamlit application.
    Streamlit will automatically detect other pages in the 'pages/' directory and display them
    as navigation links in the sidebar.
    """
    st.title("Welcome to the Quebec Road Accident Analysis App!")
    st.write(
        """
        This application provides an interactive dashboard to explore road accident data in Quebec.
        Navigate through different analyses using the sidebar on the left.
        """
    )
    st.info("👈 Select a page from the sidebar to begin your exploration.")

    st.markdown("---") # Add a separator for visual appeal

    st.header("About the Data")
    st.write(
        """
        This dashboard is built using comprehensive road accident data from Quebec,
        allowing for insights into various factors such as severity, road conditions,
        environmental factors, and temporal patterns.
        """
    )

if __name__ == "__main__":
    main()